CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_LED=y

# BT CONFIG
CONFIG_BT=y
CONFIG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DIS=y
CONFIG_BT_DIS_PNP=n
CONFIG_BT_DEVICE_NAME="nrf54lm20b_kb"
CONFIG_BT_DEVICE_APPEARANCE=768
CONFIG_BT_MAX_CONN=1

CONFIG_BT_BAS=y

CONFIG_BT_MAX_PAIRED=2

CONFIG_BT_SMP_APP_PAIRING_ACCEPT=y
CONFIG_BT_SETTINGS=y
CONFIG_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y

# Allow overwriting oldest bond when storage is full
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_BT_KEYS_SAVE_AGING_COUNTER_ON_PAIRING=y

# Increased stack due to settings API usage
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# DEBUG
CONFIG_CBPRINTF_FP_SUPPORT=y

# Disassembly listing output (build/zephyr/zephyr.lst)
CONFIG_OUTPUT_DISASSEMBLY=y
CONFIG_OUTPUT_DISASSEMBLY_WITH_SOURCE=y
CONFIG_OUTPUT_DISASSEMBLY_NO_ALIASES=y
CONFIG_OUTPUT_SYMBOLS=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y